spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laptime_page?serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      #文件的允许的大小20MB
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  type-aliases-package: com.roderick.pojo
  mapper-locations: classpath:mybatis/*.xml
#外部访问的文件上传位置
file:
  uploadFolder: F:\学习\上吊教程\Project\圈速展示\src\main\resources\static\images\vehicle
debug: true
