
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laptime_page?serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.roderick.pojo
  mapper-locations: classpath:mybatis/projectMapper.xml